/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e0e3e6",
        "tertiary": "#3e4244",
        "surface-container-low": "#eef4ff",
        "background": "#f8f9ff",
        "primary-container": "#0056b3",
        "on-error": "#ffffff",
        "surface-dim": "#d1dbec",
        "on-primary": "#ffffff",
        "tertiary-container": "#56595c",
        "on-secondary-fixed-variant": "#900038",
        "outline": "#727784",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d7e2ff",
        "on-primary-fixed": "#001a40",
        "inverse-surface": "#27313e",
        "on-surface-variant": "#424752",
        "primary": "#003f87",
        "on-secondary-fixed": "#400014",
        "on-primary-fixed-variant": "#004491",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#cdd0d3",
        "on-surface": "#121c28",
        "surface-container": "#e5eeff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#acc7ff",
        "on-background": "#121c28",
        "secondary": "#b80049",
        "secondary-container": "#e2165f",
        "inverse-primary": "#acc7ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb2be",
        "on-tertiary-fixed": "#191c1e",
        "on-secondary-container": "#fffbff",
        "surface-tint": "#115cb9",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-primary-container": "#bbd0ff",
        "surface-container-high": "#dfe9fa",
        "outline-variant": "#c2c6d4",
        "secondary-fixed": "#ffd9de",
        "surface-container-highest": "#d9e3f4",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary-fixed-variant": "#44474a",
        "surface-variant": "#d9e3f4",
        // Legacy colors fallback (mapping some to new palette)
        "success": "#10B981",
        "warning": "#ba1a1a",
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'h1': ['Inter'],
        'h2': ['Inter'],
        'h3': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-caps': ['Inter'],
        'button': ['Inter']
      },
      fontSize: {
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "button": ["15px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600"}]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      backdropBlur: {
        'xl': '12px',
        '2xl': '24px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}